excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
variable_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 0
large_tuple:
  warning: 6

